### ISSUE TITLE
Martian Winter affecting Moon

### ISSUE THREAD

**Issue by Astrasu** [Taludas/Anno2205-NewFrontiers#10] opened 2024-05-27 22:06 UTC
Hi, I have a problem concerning my moon colony: I get the martian winter (de-)buff on my moon colony. But not just for 60min, but for 60 h(!) instead, as shown in the following snipped:

![grafik](https://github.com/Taludas/Anno2205-NewFrontiers/assets/7363853/97e1ea0d-6051-4eb7-b5cc-17844da72b5b)

I do not think, getting that effect on the moon is intended (since the upside does nothing on the moon) and even if it is intented, the 60h clearly are not :D.
While this is technically not gamebreaking, since I cannot progress the main story line (because I cannot upgrade my houses), waiting for another 56h is not really feasible.

Which would be a shame, since I am really enjoying your mod so far :)

**Comment by Taludas** [comment] 2024-05-28 04:26
Hey, glad you liked it so far!
This is a duplicate of #7 

You can resolve this by using the console. I didn't find a way to make those Martin seasons not spawn on Mars, there is something hardcoded that chooses which effects can happen where that I don't know... So unfortunately no "code" solution can be found easily.

Please refer to my comment in #7 , or read the last point of the known issues list on https://taludas.github.io/#/en/Anno2205/KnownIssues

**Closed by Taludas** 2024-05-28 04:26 UTC
